version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kohina-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SEC=${SEC}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_CALLBACK=${CLIENT_CALLBACK}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - kohina-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kohina-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - kohina-network

networks:
  kohina-network:
    driver: bridge
